# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.0'

target 'ToolLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 暂时移除对自定义工具库的依赖，以确保项目能够编译
   pod 'ChimpionTools', :path => '../'
  # Pods for ToolLibrary

  target 'ToolLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToolLibraryUITests' do
    # Pods for testing
  end

end
