# SwiftLint 配置文件
# 官方文档: https://github.com/realm/SwiftLint/blob/main/README.md

# 排除的文件或目录
excluded:
  - Pods
  - .build
  - Generated
  - ToolLibraryTests
  - ToolLibraryUITests

# 包含的规则（如果设置了）
# included:

# 启用的规则
opt_in_rules:
  - colon # 冒号对齐规则
  - comma # 逗号规则
  - anyobject_protocol # 推荐使用 AnyObject 协议而不是 class-only 协议
  - array_init # 推荐使用 Array() 而不是 [] 初始化空数组
  - shorthand_operator # 推荐使用简写运算符（+=, -=, *=, /=）而不是先操作后赋值
  - closure_end_indentation # 闭包结束时的缩进一致性
  - closure_spacing # 闭包大括号前后的空格
  - contains_over_first_not_nil # 推荐使用 contains 而不是 first(where:) != nil
  - convenience_type # 推荐使用 struct/enum 代替 class for constants
  - discouraged_object_literal # 不鼓励使用字符串、数字等字面量
  - empty_count # 推荐使用 isEmpty 而不是 count == 0
  - explicit_init # 推荐使用显式初始化
  - fatal_error_message # fatalError 必须有消息
  - file_header # 文件头部注释
  - first_where # 推荐使用 first(where:) 而不是 filter { }.first
  - force_unwrapping # 尽量避免强制解包
  - force_try # 尽量避免强制 try
  - implicitly_unwrapped_optional # 尽量避免隐式解包可选类型
  - last_where # 推荐使用 last(where:) 而不是 filter { }.last
  - literal_expression_end_indentation # 字面量表达式结束时的缩进
  - modifier_order # 修饰符顺序
  - multiline_arguments # 多行参数格式
  - multiline_function_chains # 多行函数链格式
  - multiline_literal_brackets # 多行字面量括号格式
  - multiline_parameters # 多行参数格式
  - nslocalizedstring_key # 使用 NSLocalizedString 键
  - operator_usage_whitespace # 运算符使用的空白
  - override_in_extension # 在扩展中的 override
  - private_outlet # 私有 outlet
  - prohibited_super_call # 禁止的 super 调用
  - redundant_nil_coalescing # 多余的 nil 合并
  - required_enum_case # 必需的枚举情况
  - self_in_property_initialization # 在属性初始化中使用 self
  - sorted_first_last # 推荐使用 sorted { }.first/last 而不是 sorted { }.first(where:)/last(where:)
  - toggle_bool # 推荐使用 toggle() 而不是 bool = !bool
  - trailing_closure # 尾随闭包格式
  - type_name # 类型名称规则
  - unused_declaration # 未使用的声明
  - unused_import # 未使用的导入
  - untyped_error_in_catch # 在 catch 中使用未类型化的错误
  - vertical_whitespace_closing_braces # 垂直空白闭合大括号
  - vertical_whitespace_opening_braces # 垂直空白打开大括号
  - control_statement # 控制语句规则
  - trailing_comma # 尾随逗号规则

# 禁用的规则
disabled_rules:
  - file_length # 文件长度限制
  - function_body_length # 函数体长度限制
  - function_parameter_count # 函数参数数量限制
  - line_length # 行长度限制
  - nesting # 嵌套深度限制
  - todo # TODO 注释规则
  - variable_name # 变量名称规则
  - type_body_length # 类型体长度限制
  - large_tuple # 元组成员数量限制规则
# 规则配置

# 空计数规则配置
empty_count:
  severity: warning # 改为警告级别

# 圈复杂度规则配置
cyclomatic_complexity:
  warning: 10 # 警告阈值
  error: 25 # 错误阈值
  severity: warning # 改为警告级别

line_length:
  warning: 200 # 警告阈值
  error: 300 # 错误阈值
  ignores_function_declarations: true # 忽略函数声明
  ignores_comments: true # 忽略注释
  ignores_urls: true # 忽略 URL

file_length:
  warning: 500 # 警告阈值
  error: 1000 # 错误阈值
  ignore_comment_only_lines: true # 忽略只包含注释的行

type_name:
  min_length: 3 # 类型名称最小长度
  max_length: 40 # 类型名称最大长度
  severity: warning # 改为警告
  excluded:
    - T
  allowed_symbols: ["_"] # 允许下划线符号
  validates_start_with_lowercase: false # 验证以小写字母开头

identifier_name:
  allowed_symbols: ["_"] # 允许下划线符号，解决 captch_id 等变量名警告
  severity: warning # 改为警告
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

function_parameter_count:
  warning: 6
  error: 8

# 简写运算符规则配置
shorthand_operator:
  severity: warning # 改为警告级别

# 自动修正配置
autocorrect:
  enabled: true # 启用自动修正功能
  rules: # 允许自动修正的规则列表
    - colon # 冒号对齐规则
    - comma # 逗号规则
    - control_statement # 控制语句规则
    - trailing_comma # 尾随逗号规则
    - array_init
    - closure_end_indentation
    - closure_spacing
    - contains_over_first_not_nil
    - empty_count
    - explicit_init
    - first_where
    - last_where
    - type_name
    - literal_expression_end_indentation
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - operator_usage_whitespace
    - redundant_nil_coalescing
    - shorthand_operator
    - sorted_first_last
    - force_unwrapping
    - toggle_bool
    - trailing_closure
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - trailing_whitespace
    - trailing_newline

# 使用说明: 运行 swiftlint --fix 命令可自动修正符合条件的代码样式问题
# 启用分析器规则 (需要明确启用)
analyzer_rules:
  - unused_import
  - unused_declaration
  #- unused_parameter
  - unused_private_declaration
  - trailing_whitespace
  - trailing_newline
  - colon
  - comma

# 常规规则 (支持自动修复的)
rules:
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - opening_brace
  - closure_spacing
  - vertical_whitespace

nesting:
  type_level: 5
  statement_level: 5

force_cast:
  severity: warning # 默认是 error

# 缩进配置
indentation:
  width: 4 # 缩进宽度
  tab_width: 4 # Tab 宽度
  prefers_spaces: true # 优先使用空格

# 注释配置
comment:
  preferred_line_length: 120 # 注释首选行长度

# 报告配置
reporter: "xcode" # 报告格式
